// Generated by gencpp from file speech_service/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SPEECH_SERVICE_MESSAGE_ADDTWOINTS_H
#define SPEECH_SERVICE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <speech_service/AddTwoIntsRequest.h>
#include <speech_service/AddTwoIntsResponse.h>


namespace speech_service
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace speech_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_service::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::speech_service::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::speech_service::AddTwoInts > {
  static const char* value()
  {
    return "speech_service/AddTwoInts";
  }

  static const char* value(const ::speech_service::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::speech_service::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::speech_service::AddTwoInts > 
template<>
struct MD5Sum< ::speech_service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_service::AddTwoInts >::value();
  }
  static const char* value(const ::speech_service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_service::AddTwoIntsRequest> should match 
// service_traits::DataType< ::speech_service::AddTwoInts > 
template<>
struct DataType< ::speech_service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::speech_service::AddTwoInts >::value();
  }
  static const char* value(const ::speech_service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_service::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::speech_service::AddTwoInts > 
template<>
struct MD5Sum< ::speech_service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_service::AddTwoInts >::value();
  }
  static const char* value(const ::speech_service::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_service::AddTwoIntsResponse> should match 
// service_traits::DataType< ::speech_service::AddTwoInts > 
template<>
struct DataType< ::speech_service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::speech_service::AddTwoInts >::value();
  }
  static const char* value(const ::speech_service::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_SERVICE_MESSAGE_ADDTWOINTS_H
