(cl:defpackage speech_service-srv
  (:use )
  (:export
   "RETURNDETECTEDSPEECH"
   "<RETURNDETECTEDSPEECH-REQUEST>"
   "RETURNDETECTEDSPEECH-REQUEST"
   "<RETURNDETECTEDSPEECH-RESPONSE>"
   "RETURNDETECTEDSPEECH-RESPONSE"
  ))

