// Generated by gencpp from file speech_service/ReturnDetectedSpeechResponse.msg
// DO NOT EDIT!


#ifndef SPEECH_SERVICE_MESSAGE_RETURNDETECTEDSPEECHRESPONSE_H
#define SPEECH_SERVICE_MESSAGE_RETURNDETECTEDSPEECHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_service
{
template <class ContainerAllocator>
struct ReturnDetectedSpeechResponse_
{
  typedef ReturnDetectedSpeechResponse_<ContainerAllocator> Type;

  ReturnDetectedSpeechResponse_()
    : text()  {
    }
  ReturnDetectedSpeechResponse_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;




  typedef boost::shared_ptr< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReturnDetectedSpeechResponse_

typedef ::speech_service::ReturnDetectedSpeechResponse_<std::allocator<void> > ReturnDetectedSpeechResponse;

typedef boost::shared_ptr< ::speech_service::ReturnDetectedSpeechResponse > ReturnDetectedSpeechResponsePtr;
typedef boost::shared_ptr< ::speech_service::ReturnDetectedSpeechResponse const> ReturnDetectedSpeechResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speech_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_service/ReturnDetectedSpeechResponse";
  }

  static const char* value(const ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n\
\n\
";
  }

  static const char* value(const ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReturnDetectedSpeechResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_service::ReturnDetectedSpeechResponse_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_SERVICE_MESSAGE_RETURNDETECTEDSPEECHRESPONSE_H
